#!/bin/sh

formatted_print() {
  printf "\n%s" "##############################################################################"
  printf "\n%s" "# > pre-commit: $1"
  printf "\n%s" "##############################################################################"
  printf "\n" "\n"
}

# run pretty
formatted_print "Prettifying Code"
npm run pretty

# checking if npm install throws any errors or warnings
formatted_print "Installing Dependencies"
if npm run i-all | tee /dev/tty | grep -e 'npm WARN' -e 'npm ERR' > /dev/null; then
  formatted_print "Commit failed during install" > /dev/stderr
  exit 1
fi

# checking for failed unit tests
formatted_print "Running Unit Tests"
TEST_OUTPUT=$(npm run coverage)
TEST_GREP_OUTPUT=$(echo "$TEST_OUTPUT" | tee /dev/tty | grep failing) > /dev/null
if [[ -n "$TEST_GREP_OUTPUT" ]]; then
  formatted_print "Failing unit test(s) found"
  echo "$TEST_OUTPUT" | awk '/'"$TEST_GREP_OUTPUT"'/ {flag=1;next} /----------------------------|---------|----------|---------|---------|-------------------/ {flag=0} flag {print}'
  formatted_print "Commit failed during unit tests" > /dev/stderr
  exit 1
fi

COVERAGE_GREP_OUTPUT=$(npm run coverage 2>&1 | grep ERROR)
if [[ -n "$COVERAGE_GREP_OUTPUT" ]]; then
  formatted_print "Code coverage does not meet threshold"
  echo "\n$COVERAGE_GREP_OUTPUT"
  formatted_print "Commit failed during code coverage" > /dev/stderr
  exit 1
fi

# check for failing build
formatted_print "Running Build"
if ! npm run pre-commit-build | tee /dev/tty | grep 'Compiled' > /dev/null; then
  formatted_print "Commit failed on build" > /dev/stderr
  exit 1
fi

formatted_print "Running Server"
export PRE_COMMIT=true
SERVER_GREP_OUTPUT=$(node server.js 2>&1 | grep -i error)
if [[ -n "$SERVER_GREP_OUTPUT" ]]; then
  formatted_print "Failed to start server"
  echo "\n$SERVER_GREP_OUTPUT"
  formatted_print "Commit failed on server start" > /dev/stderr
  exit 1
fi

formatted_print "pre-commit completed successfully!"
