---
# tasks file for update_workspace_variables
- name: Update Workspace Variables
  uri:
        url: https://schematics.cloud.ibm.com/v1/workspaces/{{ workspace.json.id }}/template_data/{{ workspace.json.template_data[0].id }}/values
        method: PUT
        headers:
          Authorization: Bearer {{token.json.access_token}}
          Content-Type: application/json
        body_format: json
        body: 
          variablestore: "{{ variablestore }}"