---
# To run this playbook , copy this file to `vars.yml` and fill in your data
# tf_var_preshared_key is only needed for the POC template

# Terrafrom variabes
tf_var_api_key: "<api-key>"
tf_var_ssh_key: "<public-ssh-key>"
tf_var_prefix: "<unique-prefix>"
tf_var_preshared_key: "<preshared-key>" # 6-128 characters

#Schematics variables
use_existing_workspace: "<boolean>"
workspace_name: "<new-schematics-workspace-name>"  # Only needed when use_existing_workspace is false
existing_workspace_id: "<existing-schematics-workspace-id>" # Only needed when use_existing_workspace is true
action_name: "<schematics-action-name>"

template: "<craig-template-name>"
git_branch: "<branch-of-playbook>"

craig_url: https://craig.119gqgw56ti1.us-south.codeengine.appdomain.cloud/api/craig/template-tar
region: us-south
resource_group: craig-rg
variablestore: [
            {
              "name": "ibmcloud_api_key", 
              "secure": true,
              "use_default": false,
              "value": "{{tf_var_api_key}}"
            },
            {
              "name": "prefix",
              "use_default": false,
              "value": "{{tf_var_prefix}}"
            }
          ]
template_map:
  from-scratch: []
  mixed: ["ssh_key_public_key"]
  vsi: ["slz_ssh_key_public_key"]
  vsi-edge: ["slz_ssh_key_public_key"]
  power-vs-sap-hana: ["ssh_key_public_key", "power_secure_powervs_power_ssh_key_key"]
  oracle-rac: ["power_oracle_template_power_ssh_key"]
  oracle-si: ["power_oracle_template_power_ssh_key"]
  power-vs-poc: ["vsi_ssh_key_public_key", "dal10gw_on_prem_connection_preshared_key", "power_dal10_powervs_ssh_key_key"]
  quick-start-power: ["vsi_ssh_key_public_key"]
  vpnaas: []