---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: pr-template
spec:
  params:
    - name: apikey
      description: The ibmcloud api key
    - name: ibmcloud-api
      description: the ibmcloud api
      default: https://cloud.ibm.com
    - name: git-token
      description: access token for the git repo
      default: ""
    - name: target-repository
      description: the repo integration name
    - name: target-branch
      description: target branch
    - name: pr-commit-id
      description: commit id
    - name: ibmcloud-region
      description: (Optional) ibmcloud region to use
      default: ""
    - name: pipeline-debug
      description: Toggles debug mode for the pipeline
      default: "0"
    - name: registry-region
      description: (Optional) The ibmcloud container registry region
      default: ""
    - name: resource-group
      description: (Optional) Target resource group (name or id) for the ibmcloud login operation
      default: ""  
    # Event params
    - name: branch
      description: The git branch
      default: ""
    - name: commit-id
      description: commit id
      default: ""
    - name: pr-branch
      description: The branch in the forked git repo from where the PR is made
      default: ""
    - name: pr-repository
      description: The forked git repo from where the PR is made
      default: ""
    - name: repository
      description: The git repo
    # Common command related params
    - name: custom-script
      description: (Optional) A custom script to be ran prior to CRA scanning
      default: ""
    - name: env-props
      description: (Optional) A custom configuration of environment properties to source before execution, ex. 'export ABC=123 export DEF=456'
      default: ""
    - name: fileignore
      description: (Optional) Filepath to .fileignore
      default: ""
    - name: ibmcloud-trace
      description: (Optional) Enables IBMCLOUD_TRACE for ibmcloud cli logging
      default: "false"
    - name: output
      description: (Optional) Prints command result to console
      default: "false"
    - name: path
      description: Repository path to scan
      default: "/artifacts"
    - name: strict
      description: (Optional) Enables strict mode for scanning
      default: "false"
    - name: toolchainid
      description: (Optional) The target toolchain id to be used. Defaults to the current toolchain id
      default: ""
    - name: verbose
      description: (Optional) Enable verbose log messages
      default: "false"

    # BOM related params
    - name: asset-type
      description: Security checks to run (apps, image, os, all)
      default: "all"
    - name: bom-report
      description: Filepath to store generated Bill of Materials
      default: "bom.json"
    - name: docker-build-flags
      description: (Optional) Customize docker build command for build stage scanning
      default: ""
    - name: docker-registry-secret
      description: Secret to authenticate for docker-registry-url
    - name: docker-registry-url
      description: Registry url to use for docker login
      default: ""
    - name: docker-registry-username
      description: Username to authenticate for docker-registry-url
      default: ""
    - name: gradle-exclude-configs
      description: (Optional) Exclude gradle configurations, ex. 'runtimeClasspath,testCompileClasspath'
      default: ""
    - name: maven-exclude-scopes
      description: (Optional) Exclude maven scopes, ex. 'test,compile'
      default: ""
    - name: nodejs-create-package-lock
      description: (Optional) Enable the task to build the package-lock.json for node.js projects
      default: "false"
    - name: prev-report
      description: Filepath to previous BoM report to skip Dockerfile or application manifest scans
      default: ""

    # Deploy Analytic related params
    - name: deploy-report
      description: Filepath to store generated Deploy Analytic report
      default: "deploy.json"

    # Vulnerability related params
    - name: cveignore
      description: (Optional) Filepath to cveignore
      default: ""
    - name: exclude-dev
      description: (Optional) Exclude dev dependencies during vulnerability scan
      default: "false"
    - name: vulnerability-report
      description: Filepath to store Vulnerability report, not stored if empty
      default: "vulnerability.json"

    # User control params
    - name: cra-scan-image
      description: Image to use for `scan` task
      default: "icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.9"
    - name: repository
    - name: insights
    - name: region 
    - name: scripts-repo
      description: The variable storing git integration for the repository storing build and deploying source code
    - name: scripts-subpath
      description: The subpath to the script folder from the base of the git repository storing scripts folder. By default the folder path is scripts
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: v1
      kind: Secret
      metadata:
        name: cd-secret
      type: Opaque
      stringData:
        API_KEY: $(params.apikey)
        DOCKER_SECRET: $(params.docker-registry-secret)
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: pr-pipeline
        workspaces:
          - name: pipeline-ws
            persistentVolumeClaim:
              claimName: pipelinerun-$(uid)-pvc
        params:
          - name: ibmcloud-api
            value: $(params.ibmcloud-api)
          - name: git-token
            value: $(params.git-token)
          - name: pr-commit-id
            value: $(params.pr-commit-id)
          - name: target-repository
            value: $(params.target-repository)
          - name: target-branch
            value: $(params.target-branch)
          - name: ibmcloud-region
            value: $(params.ibmcloud-region)
          - name: pipeline-debug
            value: $(params.pipeline-debug)
          - name: registry-region
            value: $(params.registry-region)
          - name: resource-group
            value: $(params.resource-group)
          - name: branch
            value: $(params.branch)
          - name: commit-id
            value: $(params.commit-id)
          - name: pr-branch
            value: $(params.pr-branch)
          - name: pr-repository
            value: $(params.pr-repository)
          - name: repository
            value: $(params.repository)
          - name: custom-script
            value: $(params.custom-script)
          - name: env-props
            value: $(params.env-props)
          - name: fileignore
            value: $(params.fileignore)
          - name: ibmcloud-trace
            value: $(params.ibmcloud-trace)
          - name: output
            value: $(params.output)
          - name: path
            value: $(params.path)
          - name: strict
            value: $(params.strict)
          - name: toolchainid
            value: $(params.toolchainid)
          - name: verbose
            value: $(params.verbose)
          - name: asset-type
            value: $(params.asset-type)
          - name: bom-report
            value: $(params.bom-report)
          - name: docker-build-flags
            value: $(params.docker-build-flags)
          - name: docker-registry-url
            value: $(params.docker-registry-url)
          - name: docker-registry-username
            value: $(params.docker-registry-username)
          - name: gradle-exclude-configs
            value: $(params.gradle-exclude-configs)
          - name: maven-exclude-scopes
            value: $(params.maven-exclude-scopes)
          - name: nodejs-create-package-lock
            value: $(params.nodejs-create-package-lock)
          - name: prev-report
            value: $(params.prev-report)
          - name: deploy-report
            value: $(params.deploy-report)
          - name: cveignore
            value: $(params.cveignore)
          - name: exclude-dev
            value: $(params.exclude-dev)
          - name: vulnerability-report
            value: $(params.vulnerability-report)
          - name: cra-scan-image
            value: $(params.cra-scan-image)
          - name: insights
            value: $(params.insights) 
          - name: region
            value: $(params.region) 
          - name: scripts-repo
            value: $(params.scripts-repo)
          - name: scripts-subpath
            value: $(params.scripts-subpath)
          - name: scripts-repo-branch
            value: $(params.scripts-repo-branch)    
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-ent-pr-binding
spec:
  params:
    - name: target-repository
      value: $(event.pull_request.base.repo.clone_url)
    - name: target-branch
      value: $(event.pull_request.base.ref)
    - name: target-commit-id
      value: $(event.pull_request.base.sha)
    - name: pr-commit-id
      value: $(event.pull_request.head.sha)
    - name: pr-commit-timestamp
      value: $(event.pull_request.head.repo.pushed_at)
    - name: pr-repository
      value: $(event.pull_request.head.repo.clone_url)
    - name: pr-branch
      value: $(event.pull_request.head.ref)
    - name: pr-number
      value: $(event.pull_request.number)
    - name: pr-name
      value: $(event.pull_request.user.login)
    - name: scm-type
      value: "github-ent"
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-pr-binding
spec:
  params:
    - name: target-repository
      value: $(event.pull_request.base.repo.clone_url)
    - name: target-branch
      value: $(event.pull_request.base.ref)
    - name: target-commit-id
      value: $(event.pull_request.base.sha)
    - name: pr-commit-id
      value: $(event.pull_request.head.sha)
    - name: pr-commit-timestamp
      value: $(event.pull_request.head.repo.pushed_at)
    - name: pr-repository
      value: $(event.pull_request.head.repo.clone_url)
    - name: pr-branch
      value: $(event.pull_request.head.ref)
    - name: pr-number
      value: $(event.pull_request.number)
    - name: pr-name
      value: $(event.pull_request.user.login)
    - name: scm-type
      value: "github"
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: gitlab-pr-binding
spec:
  params:
    - name: target-repository
      value: "$(event.object_attributes.target.git_http_url)"
    - name: target-branch
      value: "$(event.object_attributes.target_branch)"
    - name: target-commit-id
      value: $(event.merge_request.base.sha)
    - name: pr-repository
      value: "$(event.object_attributes.source.git_http_url)"
    - name: pr-branch
      value: "$(event.object_attributes.source_branch)"
    - name: pr-commit-id
      value: "$(event.object_attributes.last_commit.id)"
    - name: pr-commit-timestamp
      value: $(event.object_attributes.last_commit.timestamp)
    - name: pr-number
      value: $(event.object_attributes.iid)
    - name: pr-name
      value: $(event.user.username)
    - name: project-id
      value: $(event.project.id)
    - name: scm-type
      value: "gitlab"
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-pr-listener
spec:
  triggers:
    - bindings:
        - name: github-pr-binding
      template:
        name: pr-template
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: gitlab-pr-listener
spec:
  triggers:
    - bindings:
        - name: gitlab-pr-binding
      template:
        name: pr-template
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-pr-listener
spec:
  triggers:
    - bindings:
        - name: github-ent-pr-binding
      template:
        name: pr-template
