---
# To run the playbook locally, run `ansible-playbook main.yml` in this directory.
# This playbook creates a schematics workspace, uploads a craig .tar file for a specific template to 
# that workspace, generates a plan, applies the plan to create the resources in the template, and destroys 
# the newly created resources.
# If any step fails, the playbook will stop and print the error to the terminal.

- name: Create and prepare schematics workspace for CRAIG template deployment
  hosts: localhost
  vars_files: 
    - ./vars/vars.template.yml
    - ./vars/template_override_vars/{{template}}.yml
  roles:
    - role: get_iam_token
    - role: download_tar
    - role: create_schematics_workspace
      vars:
        description: Automated CRAIG Testing Workspace
    - role: upload_tar
- name: Update workspace variables
  hosts: localhost
  vars_files: ./vars/vars.template.yml
  roles:
    - role: update_variablestore
    - role: update_workspace_variables
- name: Deploy CRAIG terraform template
  hosts: localhost
  vars_files: ./vars/vars.template.yml
  roles:
    - role: get_iam_token
    - role: action
      vars:
        action_type: plan
    - role: get_iam_token
    - role: await_action
      vars:
        action_type: plan
        register_name: await_plan
    - role: get_iam_token
    - role: action
      vars:
        action_type: apply
    - role: get_iam_token
    - role: await_action
      vars:
        action_type: apply
        register_name: await_apply
    - role: get_iam_token
    - role: action
      vars:
        action_type: destroy
    - role: await_action
      vars:
        action_type: destroy
        register_name: await_destroy
- name: Retry destroy on failure
  hosts: localhost
  vars_files: ./vars/vars.template.yml
  roles:
    - role: pause
      when: job_status == "job_failed"
      vars:
        pause_time: 5
    - role: get_iam_token
      when: job_status == "job_failed"
    - role: action
      when: job_status == "job_failed"
      vars:
        action_type: destroy
    - role: await_action
      when: job_status == "job_failed"
      vars:
        action_type: destroy
        register_name: await_destroy
- name: Delete Schematics Workspace
  hosts: localhost
  vars_files: ./vars/vars.template.yml
  roles:
    - role: get_iam_token
    - role: delete_schematics_workspace
      when: job_status != "job_failed"