---
# To setup this directory to run locally, copy /vars/vars.template.yml to /vars/vars.yml and fill in needed
# values
# To run the playbook locally, run `ansible-playbook main.yml` in this directory.
# This playbook creates a schematics workspace, uploads a craig .tar file for a specific template to 
# that workspace, generates a plan, applies the plan to create the resources in the template, and destroys 
# the newly created resources.
# If any step fails, the playbook will stop and print the error to the terminal.

- name: Upload CRAIG template to schematics workspace
  hosts: localhost
  vars_files: ./vars/vars.yml
  roles:
    - role: get_iam_token
    - role: download_tar
    - role: create_schematics_workspace
      vars:
        description: Automated CRAIG Testing Workspace
        tags: ["craig"]
- name: TODO - convert to roles
  hosts: localhost
  vars_files: ./vars/vars.yml
  tasks: 
    - name: Upload {{template}}.tar to Schematics Workspace
      command: "curl -s --request PUT \
                --url 'https://schematics.cloud.ibm.com/v1/workspaces/{{ workspace.json.id }}/template_data/{{ workspace.json.template_data[0].id }}/template_repo_upload' \
                -H 'Authorization: Bearer {{ token.json.access_token }}' \
                -H 'Content-Type: multipart/form-data' \
                --form 'file=@{{playbook_dir}}/{{template}}.tar'"
      async: 120
    - name: Wait until {{template}}.tar has been successfully uploaded
      uri:
        url: https://schematics.cloud.ibm.com/v1/workspaces/{{ workspace.json.id }}
        method: GET
        body_format: json
        headers:
          Authorization: Bearer {{token.json.access_token}}
      register: workspace_status
      until: workspace_status.json.status == "INACTIVE"
      delay: 10
      retries: 50
    - name: Update variablestore
      set_fact:
        variablestore: "{{ variablestore +  [{'name': item, 'secure': true, 'use_default': false,  'value': ssh_key}] }}"
      loop: "{{template_map[template]}}"
    - name: Update vars in workspace
      uri:
        url: https://schematics.cloud.ibm.com/v1/workspaces/{{ workspace.json.id }}/template_data/{{ workspace.json.template_data[0].id }}/values
        method: PUT
        headers:
          Authorization: Bearer {{token.json.access_token}}
          Content-Type: application/json
        body_format: json
        body: 
          variablestore: "{{ variablestore }}"
- name: Start generate plan action
  hosts: localhost
  vars_files: ./vars/vars.yml
  roles:
    - role: get_iam_token
    - role: action
      vars:
        action: plan
    - role: get_iam_token
    - role: await_action
      vars:
        action: plan
        register_name: await_plan
    - role: get_iam_token
    - role: action
      vars:
        action: apply
    - role: get_iam_token
    - role: await_action
      vars:
        action: apply
        register_name: await_apply
    - role: get_iam_token
    - role: action
      vars:
        action: destroy
    - role: get_iam_token
    - role: await_action
      vars:
        action: destroy
        register_name: await_destroy