# This playbook creates an action in schematics, and runs the action using vars
# in vars/vars.yml The action then runs the main.yml playbook by fetching it
# from the CRAIG enterprise github

- name: Run end to end test inside a schematics action
  hosts: localhost
  vars_files: ./vars/vars.yml
  roles:
    - role: get_iam_token
    - role: create_schematics_action
      vars:
        source:
          source_type: git_hub_enterprise
          git:
            git_repo_url: https://github.ibm.com/platinum-developer-tools/CRAIG.git
            git_repo_folder: ansible/template-test
            git_branch: "{{ git_branch }}"
        inputs:
          - name: template
            value: "{{ template }}"
          - name: tf_var_api_key
            value: "{{ tf_var_api_key }}"
            metadata:
              secure: true
          - name: tf_var_prefix
            value: "{{ tf_var_prefix }}"
          - name: workspace_name
            value: "{{ workspace_name }}"
          - name: tf_var_preshared_key
            value: "{{ tf_var_preshared_key | default('NONE') }}"
            metadata:
              secure: true
          - name: tf_var_ssh_key
            value: "{{ tf_var_ssh_key | default('NONE') }}"
          - name: tf_var_power_ssh_key
            value: "{{ tf_var_power_ssh_key | default('NONE') }}"
          - name: use_existing_workspace
            value: "{{ use_existing_workspace | default('false')}}"
          - name: existing_workspace_id
            value: "{{ existing_workspace_id | default('NONE') }}"
    - role: run_schematics_action