---
# tasks file for download_tar
- name: Download tar to current directory
  uri:
    url: "{{craig_url}}/{{template}}"
    method: POST
    body_format: json
    body: "{{ override_craig | default({}) }}"
    status_code: 200
    dest: "{{playbook_dir}}/{{template}}.tar"
    timeout: 500
