---
# tasks file for get_iam_token
- name: Get IAM Access Token
  uri:
    url: https://iam.cloud.ibm.com/identity/token
    method: POST
    headers:
      Content-Type: application/x-www-form-urlencoded
    body: "grant_type=urn:ibm:params:oauth:grant-type:apikey&apikey={{api_key}}"
  register: token
