- name: Ensure {{ action_type }} finishes
  uri:
    url: https://schematics.cloud.ibm.com/v2/jobs/{{ action_result.json.activityid }}
    method: GET
    body_format: json
    headers:
      Authorization: Bearer {{ token.json.access_token }}
  register: dynamic_value
  until: dynamic_value.json.status.workspace_job_status.status_code == "job_finished" or dynamic_value.json.status.workspace_job_status.status_code == "job_failed"
  delay: 120
  retries: 50
- name: Register status code
  set_fact:
    job_status: "{{dynamic_value.json.status.workspace_job_status.status_code}}"
- name: Force failure if job fails and is not destroy
  ansible.builtin.fail:
    msg: Terraform "{{ action_type }}" failed
  when:
    - action_type != "destroy"
    - job_status == "job_failed"
