override_craig:
  atracker:
    enabled: false
    type: cos
    name: atracker
    target_name: atracker-cos
    bucket: atracker-bucket
    add_route: true
    cos_key: cos-bind-key
    locations:
    - global
    - us-south
    instance: false
    plan: lite
    resource_group: 
    archive: false
  transit_gateways:
    - name: transit-gateway
      resource_group: service-rg
      global: false
      connections: []
      use_data: false
      prefix_filters: []
      gre_tunnels: []
      crns: 
      classic: false
  vsi:
    - kms: kms
      encryption_key: key
      image: ibm-ubuntu-22-04-4-minimal-amd64-1
      image_name: Ubuntu Linux 22.04 LTS Jammy Jellyfish Minimal Install
      profile: bx2-2x8
      name: example-deployment
      security_groups:
      - management-vsi
      ssh_keys:
      - vsi-ssh-key
      vpc: management
      vsi_per_subnet: 1
      resource_group: management-rg
      override_vsi_name: 
      user_data: 
      network_interfaces: []
      subnets:
      - vsi-zone-1
      volumes: []
      subnet: ''
      enable_floating_ip: false
      primary_interface_ip_spoofing: false
      use_variable_names: false
      snapshot: 
      use_snapshot: false