---
# tasks file for update_variablestore
- name: Update variablestore
  set_fact:
    variablestore: "{{ variablestore +  [{'name': item, 'secure': true, 'use_default': false,  'value': tf_var_ssh_key}] }}"
  loop: "{{template_map[template]}}"