---
# tasks file for update_variablestore
- name: Update variablestore
  set_fact:
    variablestore: "{{ variablestore +  [{'name': item, 'secure': false, 'use_default': false,  'value': vars[ssh_key_map[item]] }] }}"
  loop: "{{template_map[template]}}"

